apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "iperf-sink.fullname" . }}
  namespace: {{ .Values.labels.namespace }}
  labels:
    app: {{ template "iperf-sink.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    {{ if .Values.VXLAN.enabled }}
    {{ .Values.VXLAN.selector }}: "true"
    {{ end }}
  {{ if .Values.VXLAN.enabled }}
  annotations:
    {{ .Values.VXLAN.selector }}/networks: {{ .Values.VXLAN.interface }}
  {{ end }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "iperf-sink.name" . }}
        release: {{ .Release.Name }}
      {{ if .Values.VXLAN.enabled }}
        {{ .Values.VXLAN.selector }}: "true"
      annotations:
        {{ .Values.VXLAN.selector }}/networks: {{ .Values.VXLAN.interface }}
      {{ end }}
    spec:
      {{ if .Values.VXLAN.enabled }}
      initContainers:
      - name: {{ .Values.VXLAN.name }}-init
        image: {{ .Values.VXLAN.image.repository }}:{{ .Values.VXLAN.image.tag }}
        imagePullPolicy: {{ .Values.VXLAN.image.pullPolicy }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command:
        - bash
        - -c
        - |
          set -x
          # set GRO settings off
          ethtool -K {{ .Values.VXLAN.interface }} gro off
      - name: network-setup
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
          privileged: true
        command: ["/bin/sh"]
        args:
        - -c
        - |
          set -xe
          ip a
          ip a add {{ .Values.VXLAN.ip }} dev {{ .Values.VXLAN.interface }}
          ip route add {{ .Values.k8s.network }} via {{ .Values.k8s.via }}
          ip route change default via {{ .Values.k8s.gw }}
          ip link set dev eth0 mtu 1440
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
          - name: MODE
            value: {{ quote .Values.iperf.MODE }}
          - name: PORT
            value: {{ quote .Values.iperf.PORT }}
          - name: DAEMON
            value: {{ quote .Values.iperf.DAEMON }}
          - name: OPTIONS
            value: {{ quote .Values.iperf.OPTIONS }}
        {{ if .Values.VXLAN.enabled }}
        - name: vxlan-controller-agent
          image: {{ .Values.VXLAN.image.repository }}:{{ .Values.VXLAN.image.tag }}
          imagePullPolicy: {{ .Values.VXLAN.image.pullPolicy }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          resources:
            requests:
              cpu: "{{ .Values.VXLAN.resources.cpu }}"
        {{ end }}
